import { useEffect, useState } from 'react'
import { listClients, createClient, deleteClient } from '../lib/api'
import type { Client } from '../lib/types'
import { Link } from 'react-router-dom'
export default function Clients(){ const[rows,setRows]=useState<Client[]>([]); const[show,setShow]=useState(false)
  const refresh=async()=>setRows(await listClients()); useEffect(()=>{refresh()},[])
  const onCreate=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault(); const f=new FormData(e.currentTarget); await createClient({name:String(f.get('name')),segment:String(f.get('segment')||'HNI') as any,owner:String(f.get('owner')||'You'),notes:String(f.get('notes')||'')} as any); setShow(false); refresh()}
  return(<div className='space-y-4'><div className='flex items-center justify-between'><h1 className='text-xl font-semibold'>Clients</h1><button className='btn' onClick={()=>setShow(true)}>New client</button></div>
  <div className='card p-0 overflow-hidden'><table className='min-w-full'><thead className='bg-gray-50 text-left text-sm text-gray-600'><tr><th className='px-4 py-3'>Name</th><th className='px-4 py-3'>Segment</th><th className='px-4 py-3'>Owner</th><th className='px-4 py-3'></th></tr></thead><tbody>{rows.map(c=>(<tr key={c.id} className='border-t'><td className='px-4 py-3'><Link className='text-brand-700 font-medium' to={`/clients/${c.id}`}>{c.name}</Link></td><td className='px-4 py-3'>{c.segment}</td><td className='px-4 py-3'>{c.owner}</td><td className='px-4 py-3 text-right'><button className='text-sm text-red-600' onClick={async()=>{await deleteClient(c.id); refresh()}}>Delete</button></td></tr>))}</tbody></table></div>
  {show&&(<div className='fixed inset-0 bg-black/40 grid place-items-center' onClick={()=>setShow(false)}><div className='card w-full max-w-lg' onClick={e=>e.stopPropagation()}><div className='text-lg font-semibold mb-3'>New client</div><form onSubmit={onCreate} className='space-y-3'><div><label className='label'>Name</label><input className='input' name='name' required/></div><div className='grid grid-cols-2 gap-3'><div><label className='label'>Segment</label><select name='segment' className='input'><option>HNI</option><option>Institutional</option><option>Retail</option></select></div><div><label className='label'>Owner</label><input className='input' name='owner' defaultValue='You'/></div></div><div><label className='label'>Notes</label><textarea className='input' name='notes' rows={3}></textarea></div><div className='flex justify-end gap-2'><button type='button' className='px-3 py-2 rounded-lg border' onClick={()=>setShow(false)}>Cancel</button><button className='btn'>Create</button></div></form></div></div>)}
  </div>) }